# https://realpython.com/python-project-documentation-with-mkdocs/
# to deploy:
# commit a change with __version__ in setup.py and src/__init__.py
# wait for wheels to build and download them 
# twine upload dist/*
# label as new release
# bash docs/create_docs.sh
# mike deploy --update-aliases --rebase --push [VERSION NUMBER] latest
# https://mkdocstrings.github.io/python/usage/
site_name: Fast CoDy
theme:
#  favicon: assets/images/favicon.png
  palette:
    primary: red
  name: "material"
  features:
    - navigation.sections
plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [src, src/fast_cd]
        options:
          heading_level: 2
          show_root_toc_entry: false
          show_root_heading: false
          show_signature_annotations: false
          # show_signature: false
          docstring_style: "numpy"
repo_url: https://github.com/otmanon/fast_cd_pyb/
repo_name: otmanon/fast_cd_pyb/
extra:
  analytics:
    provider: google
    property: G-YDMBBH2H8E
  version:
    provider: mike
# https://github.com/jimporter/mike